version: "3.9"

services:
  postgres:
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
  social-network:
    depends_on:
      - postgres
    image: social-network:0.1.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DATABASE_HOST=postgres