version: "3.9"

networks:
  pg-net:
    name: pgnet
    ipam:
      config:
        - subnet: "192.168.0.0/24"
services:
  pg-master:
    container_name: pgmaster
    networks:
      - pg-net
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
    command: [ "postgres", "-c", "log_statement=all" ]
  redis-master:
    container_name: redismaster
    networks:
      - pg-net
    image: redis:alpine3.18
    ports:
      - "6379:6379"
  social-network:
    networks:
      - pg-net
    depends_on:
      - pg-master
      - redis-master
    image: social-network:0.1.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DATABASE_HOST=pgmaster
      - REDIS_HOST=redismaster