{
 "title": "RED",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{status=\"200\"}) / sum(http_server_requests_seconds_count{status=\"200\"})",
     "legendFormat": "200 ok"
    },
    {
     "expr": "sum(http_server_requests_seconds_sum{status!=\"200\"}) / sum(http_server_requests_seconds_count{status!=\"200\"})",
     "legendFormat": "Non 200 Ok"
    },
    {
     "expr": "sum(http_server_requests_seconds_sum) / sum(http_server_requests_seconds_count)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!=\"200\"}[$__rate_interval])",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[$__rate_interval])",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  }
 ]
}