spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${spring.datasource.username}
    username: test_user
    password: test_pass
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    defaultSchema: public
    changeLog: classpath:/db/changelog/changelog-master.yaml
# Redis Config
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:}
#Tarantool Config
tarantool:
   host: ${TARANTOOL_HOST:localhost}
   port: ${TARANTOOL_PORT:3301}
   username: ${TARANTOOL_USER_NAME:test_user}
   password: ${TARANTOOL_USER_PASSWORD:test_password}
#logging:
#  level:
#    org.springframework.jdbc.core: TRACE