spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${spring.datasource.username}
    username: test_user
    password: test_pass
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    defaultSchema: public
    changeLog: classpath:/db/changelog/changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
cache:
  ttl: ${COUNTER_TTL_MINUTES:1}
server:
  port: ${SERVICE_PORT:8080}